//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnologiaMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuota()
        {
            this.DetalleCuota = new HashSet<DetalleCuota>();
        }
    
        public int Id { get; set; }
        public string Cod_Cuota { get; set; }
        public System.DateTime Fecha { get; set; }
        public double TotalAbonado { get; set; }
        public int TipoPagoId { get; set; }
        public int RentaId { get; set; }
    
        public virtual TipoPago TipoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCuota> DetalleCuota { get; set; }
        public virtual Renta Renta { get; set; }
    }
}
