//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnologiaMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCuota
    {
        public int Id { get; set; }
        public string Volumen_Impreso { get; set; }
        public string Subtotal { get; set; }
        public int CuotaId { get; set; }
    
        public virtual Cuota Cuota { get; set; }
    }
}
