//------------------------------------------------------------------------------//
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnologiaMT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloContainer : DbContext
    {
        public ModeloContainer()
            : base("name=ModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<EstadoFactura> EstadoFacturas { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVentas { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompras { get; set; }
        public virtual DbSet<Proveedor> Proveedores { get; set; }
        public virtual DbSet<RazonSocial> RazonSociales { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Renta> Rentas { get; set; }
        public virtual DbSet<DetalleRenta> DetalleRentas { get; set; }
        public virtual DbSet<AsistenciaTecnica> AsistenciaTecnicas { get; set; }
        public virtual DbSet<DetallaAsistenciaTecnica> DetallaAsistenciaTecnicas { get; set; }
        public virtual DbSet<Retencion> Retenciones { get; set; }
        public virtual DbSet<TipoPago> TipoPagos { get; set; }
        public virtual DbSet<TipoFactura> TipoFacturas { get; set; }
        public virtual DbSet<Cuota> Cuotas { get; set; }
        public virtual DbSet<Estado_Producto> Estado_Productos { get; set; }
        public virtual DbSet<DetalleCuota> DetalleCuotas { get; set; }
        public virtual DbSet<Descuento> Descuentos { get; set; }
    }
}
